### ISSUE TITLE
I need to install it manually

### ISSUE THREAD

**Issue by hopewise** [stracker-phil/wp-debug-redirect#3]
I have an issue here: https://wordpress.stackexchange.com/questions/350338/i-get-redirected-too-many-times-only-in-wp-admin

I tried to use your script and install it manually as: https://perishablepress.com/activate-wordpress-plugin-database/

but it did not work.. and I can't access wp-admin already .. 

I have tried to install it manually in DB by updating the option_name active_plugins as:

    a:1:{i:0;s:20:"akismet/redirect.php";}

and copied your file `redirect.php` to `akismet/` folder, so its at `wp-content/plugins/akismet/redirect.php`

I hope I can fix my issue using your script

any idea?

**Comment by stracker-phil** [comment]
Hi @hopewise 

thanks for getting in touch :-)

When your wp-admin area is not accessible, I suggest installing the redirect.php script as a [mu-plugin](https://wordpress.org/support/article/must-use-plugins/):
- create the folder /wp-content/mu-plugins
- save the redirect.php file right into that folder (i.e., wp-content/mu-plugins/redirect.php)

Unfortunately, I cannot help you with the Nginx configuration or the redirect loop that you mention in your StackExchange post...

Hopefully, the redirect.php script can shed some light on the issue. Philipp :)

**Comment by hopewise** [comment]
thanks, I already solved the redirect issue, it was because my nginx server is behind an aws application load balancer.. wp was trying to redirect for https, while I pass traffic to it using port 80..
